/* Extended controls use the same backend bridge and theme as the original page. */
let chosenTimerTrack=null,chosenIdleTrack=null,musicDestination='alarm',musicReturnFocus=null,homeCatalog={devices:[],scenarios:[]},homeRows=[],editingHome=null,homeRevision=0,homePending=0,extraSequence=0;
const originalRenderAlarm=renderAlarm;
renderAlarm=function(s,c){originalRenderAlarm(s,c);if(!document.activeElement.closest('#panel-alarm')){if((s.sound_path||'').startsWith('music://')){$('soundPath').value='Astra Music: '+(s.sound_name||'выбранный трек');$('alarmMusicLabel').textContent=s.sound_name||'Музыка из Astra Music';}else{$('alarmMusicLabel').textContent=s.sound_name?'Локальный файл: '+s.sound_name:'Можно использовать локальный файл или трек из подключённой Яндекс Музыки / VK.';}}};
// The engine retains the actual sound source; the form displays its readable name.
$('saveAlarm').onclick=async()=>{const button=$('saveAlarm');button.disabled=true;try{const [hour,minute]=$('alarmTime').value.split(':').map(Number),days=[...document.querySelectorAll('#days input:checked')].map(x=>Number(x.value));if(!days.length)throw Error('Выберите хотя бы один день');await checkedCall('alarm_set',{hour,minute,repeat:$('alarmRepeat').value==='true',interval:Number($('alarmInterval').value)||5,sound_path:'',days_of_week:days});notice('alarmNotice','Расписание сохранено','ok');await refresh();}catch(e){notice('alarmNotice',e.message,'error');}finally{button.disabled=false;}};
const labels={playpause:'Медиа play/pause',shutdown:'Выключить ПК',sleep:'Сон',close_app:'Закрыть приложение',hotkey:'Комбинация клавиш',astra_command:'Команда Astra',music:'Включить музыку',music_pause:'Пауза музыки'};
async function checkedCall(method,args={}){const mutation=['home_schedule_save','home_schedule_remove'].includes(method);if(mutation){homeRevision++;homePending++;}try{const result=await call(method,args);if(result?.error)throw Error(result.error);if(!result||typeof result!=='object')throw Error('Плагин вернул пустой ответ: '+method);return result;}finally{if(mutation){homeRevision++;homePending--;}}}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function actionButton(text,run){const b=node('button',text,'small');b.type='button';b.onclick=async()=>{b.disabled=true;try{await run();}catch(e){notice('timerNotice',e.message,'error');}finally{b.disabled=false;}};return b;}
const originalRenderTimer=renderTimer;
const reportedTimerResults=new Map();
renderTimer=function(s){originalRenderTimer(s);timerState=s;const list=$('timerList');
  for(const active of s.timers||[])reportedTimerResults.delete(active.id);
  for(const result of s.finished||[]){const stamp=result.generation+'|'+result.outcome+'|'+result.info;if(reportedTimerResults.get(result.id)!==stamp){reportedTimerResults.set(result.id,stamp);notice('timerNotice',(result.name||'Таймер')+': '+(result.info||'Действие завершено'),result.outcome==='error'?'error':'ok');}}
  const rows=(s.timers||[s]).filter(t=>t.running||t.executing);const stamp=JSON.stringify(rows);if(list.dataset.stamp===stamp)return;list.dataset.stamp=stamp;
  // Update values in place so keyboard focus survives the one-second refresh.
  const ids=new Set(rows.map(t=>t.id));for(const child of [...list.children])if(!ids.has(child.dataset.id))child.remove();
  if(!rows.length){list.append(node('p','Нет активных таймеров','empty'));return;}
  for(const t of rows){let card=[...list.children].find(c=>c.dataset.id===t.id);if(!card){card=node('div',undefined,'timer-entry');card.dataset.id=t.id;card.append(node('strong'),node('span','','remaining'),node('p','','meta'),node('div',undefined,'actions'));list.append(card);}
    card.children[0].textContent=t.name||'Таймер';card.children[1].textContent=t.executing?'…':fmt(t.remaining_seconds);card.children[2].textContent=(t.executing?'Выполняется · ':t.paused?'На паузе · ':'Идёт · ')+(labels[t.action]||t.action||'');card.children[2].title=card.children[2].textContent;
    const controls=card.children[3],mode=t.running?(t.paused?'paused':'running'):'idle';if(controls.dataset.mode!==mode){controls.dataset.mode=mode;controls.replaceChildren();if(t.running){controls.append(actionButton(t.paused?'Продолжить':'Пауза',async()=>{await checkedCall(t.paused?'resume':'pause',{timer_id:t.id});await refresh();}),actionButton('Отменить',async()=>{await checkedCall('cancel',{timer_id:t.id});await refresh();}));}}
  }
};
function syncAction(){const a=$('timerAction').value;$('hotkeyField').hidden=a!=='hotkey';$('commandField').hidden=a!=='astra_command';$('timerMusicField').hidden=a!=='music';}
$('timerAction').addEventListener('change',syncAction);
// Inactivity has the same actions and parameters as a countdown.
for(const action of ['close_app','hotkey','astra_command','music','music_pause']){const option=node('option',labels[action]);option.value=action;$('idleAction').append(option);}
const idleFields=node('div'),idleCard=$('idleAction').closest('article');idleFields.id='idleFields';idleCard.insertBefore(idleFields,$('idleStatus'));
function idleField(id,label,placeholder){const field=node('div',undefined,'field'),l=node('label',label),input=node('input');l.htmlFor=id;input.id=id;input.placeholder=placeholder;field.id=id+'Field';field.append(l,input);idleFields.append(field);return input;}
idleField('idleWindow','Окно приложения','Точный заголовок окна или его часть');
idleField('idleKeys','Сочетание клавиш','Например, Ctrl+Alt+P');
idleField('idleCommandKey','Метка автоматизации Astra','Например, вечер');
const idleMusic=node('div');idleMusic.id='idleMusicField';const idleChoose=node('button','Музыка из Astra Music'),idleLabel=node('p','Выберите трек','meta');idleChoose.id='idleMusicChoose';idleLabel.id='idleMusicLabel';idleMusic.append(idleChoose,idleLabel);idleFields.append(idleMusic);
const idleCommandHint=node('p','В «Командах» Astra свяжите нужные действия с событием «Завершение таймера: команда Astra» и фильтром command_key, равным этой метке.','hint');idleCommandHint.id='idleCommandHint';idleFields.append(idleCommandHint);
function syncIdle(){const a=$('idleAction').value;$('idleWindowField').hidden=!['playpause','close_app','hotkey'].includes(a);$('idleKeysField').hidden=a!=='hotkey';$('idleCommandKeyField').hidden=a!=='astra_command';$('idleCommandHint').hidden=a!=='astra_command';$('idleMusicField').hidden=a!=='music';}
function idleParams(){const a=$('idleAction').value;if(a==='close_app')return {window:$('idleWindow').value};if(a==='hotkey')return {keys:$('idleKeys').value,window:$('idleWindow').value};if(a==='astra_command')return {command_key:$('idleCommandKey').value};if(a==='music'){if(!chosenIdleTrack)throw Error('Выберите музыку для бездействия');return chosenIdleTrack;}return {};}
$('idleAction').addEventListener('change',syncIdle);
let settingsDraftRevision=0;
function markSettingsDirty(){settingsDraftRevision++;window.settingsFormDirty=true;}
for(const event of ['input','change'])$('panel-settings').addEventListener(event,e=>{if(!['screenCommentary','screenIntervalMin','screenIntervalMax'].includes(e.target.id))markSettingsDirty();});
const originalRenderSettings=renderSettings;
renderSettings=function(s){originalRenderSettings(s);if(!settingsFormEditing()){const q=s.settings||{},p=q.idle_action_params||{};$('idleWindow').value=q.idle_window||p.window||'';$('idleKeys').value=p.keys||'';$('idleCommandKey').value=p.command_key||'';chosenIdleTrack=p.track_id?p:null;$('idleMusicLabel').textContent=chosenIdleTrack?(p.artist||'')+' — '+(p.title||p.track_id):'Выберите трек';syncIdle();syncAction();}if(s.idle?.error){$('idleStatus').textContent='Ошибка: '+s.idle.error;}};
$('idleStart').onclick=async()=>{const b=$('idleStart');b.disabled=true;try{await checkedCall('idle_start',{minutes:Number($('idleMinutes').value),action:$('idleAction').value,window:$('idleWindow').value,action_params:idleParams()});notice('idleNotice','Отслеживание включено','ok');await refresh();}catch(e){notice('idleNotice',e.message,'error');}finally{b.disabled=false;}};
$('saveSettings').onclick=async()=>{try{if(screenSavedRevision<screenDraftRevision&&!await saveScreenSettings())throw Error('Не удалось сохранить комментарии по экрану');const revision=settingsDraftRevision;await checkedCall('settings_save',{default_action:$('defaultAction').value,default_window:$('defaultWindow').value,idle_minutes:Number($('idleMinutes').value)||30,idle_action:$('idleAction').value,idle_window:$('idleWindow').value,idle_action_params:idleParams()});if(revision===settingsDraftRevision)window.settingsFormDirty=false;notice('settingsNotice','Настройки сохранены локально','ok');}catch(e){notice('settingsNotice',e.message,'error');}};
$('timerStart').onclick=async()=>{const b=$('timerStart');b.disabled=true;try{const action=$('timerAction').value;let params={};if(action==='hotkey')params={keys:$('hotkeyKeys').value,window:$('timerWindow').value};if(action==='close_app'){if(!$('timerWindow').value)throw Error('Выберите приложение в списке окон');params={window:$('timerWindow').selectedOptions[0]?.textContent.replace(/^#\d+ — /,'')||''};}if(action==='astra_command')params={command_key:$('commandKey').value};if(action==='music'){if(!chosenTimerTrack)throw Error('Выберите музыку');params=chosenTimerTrack;}
  const result=await checkedCall('timer_start_local',{hours:Number($('hours').value),minutes:Number($('minutes').value),seconds:Number($('seconds').value),action,window:$('timerWindow').value,name:$('timerName').value,action_params:params});notice('timerNotice','Добавлен таймер «'+result.name+'»','ok');await refresh();
}catch(e){notice('timerNotice',e.message,'error');}finally{b.disabled=false;}};
$('timerPause').hidden=true;$('timerCancel').hidden=true;
function openMusic(destination){musicDestination=destination;musicReturnFocus=document.activeElement;$('musicModal').classList.add('open');notice('musicNotice');$('musicQuery').focus();}
function closeMusic(){$('musicModal').classList.remove('open');musicReturnFocus?.focus();}
$('alarmMusicChoose').onclick=()=>openMusic('alarm');$('timerMusicChoose').onclick=()=>openMusic('timer');$('musicClose').onclick=closeMusic;
$('idleMusicChoose').onclick=()=>openMusic('idle');
async function chooseTrack(track){if(!track?.track_id)throw Error('В плагине «Музыка» не выбран трек');const clean={service:track.service||$('musicService').value,track_id:String(track.track_id),title:track.title||'',artist:track.artist||'',extra:track.extra||{}};
  if(musicDestination==='alarm'){const r=await checkedCall('alarm_music_save',{track:clean});$('soundPath').value=r.sound_path||'';$('alarmMusicLabel').textContent=clean.artist+' — '+clean.title;notice('alarmNotice','Мелодия из Astra Music сохранена','ok');}else if(musicDestination==='idle'){markSettingsDirty();chosenIdleTrack=clean;$('idleMusicLabel').textContent=clean.artist+' — '+clean.title;}else{chosenTimerTrack=clean;$('timerMusicLabel').textContent=clean.artist+' — '+clean.title;}closeMusic();}
$('musicSearch').onclick=async()=>{const b=$('musicSearch');b.disabled=true;try{notice('musicNotice','Поиск…');const r=await checkedCall('music_search',{query:$('musicQuery').value,service:$('musicService').value});$('musicResults').replaceChildren();for(const track of r.tracks||[]){const b=node('button',(track.artist||'')+' — '+(track.title||track.track_id));b.onclick=()=>chooseTrack(track).catch(e=>notice('musicNotice',e.message,'error'));$('musicResults').append(b);}notice('musicNotice',(r.tracks||[]).length?'Выберите трек':'Треки не найдены');}catch(e){notice('musicNotice',e.message,'error');}finally{b.disabled=false;}};
$('musicUseCurrent').onclick=async()=>{try{await chooseTrack(await checkedCall('music_current'));}catch(e){notice('musicNotice',e.message,'error');}};
$('musicQuery').onkeydown=e=>{if(e.key==='Enter')$('musicSearch').click();};
$('musicModal').onclick=e=>{if(e.target===$('musicModal'))closeMusic();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('musicModal').classList.contains('open'))closeMusic();if(e.key==='Tab'&&$('musicModal').classList.contains('open')){const elements=[...$('musicModal').querySelectorAll('button,input,select')].filter(n=>!n.disabled),first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}});
function populateHomeTargets(){const select=$('homeTarget'),old=select.value;select.replaceChildren();const rows=$('homeKind').value==='scenario'?homeCatalog.scenarios:homeCatalog.devices;for(const item of rows||[]){const o=node('option',item.name||item.id);o.value=item.id;select.append(o);}if([...select.options].some(o=>o.value===old))select.value=old;populateCapabilities();}
function selectedDevice(){return homeCatalog.devices.find(d=>d.id===$('homeTarget').value);}
function scheduleCapabilities(device){const result=[];for(const cap of device?.capabilities||[]){const p=cap.parameters||{},instance=p.instance||cap.state?.instance;const push=(name,control,parameters=p)=>result.push({...cap,control,parameters:{...parameters,instance:name},state:{instance:name,value:cap.state?.instance===name?cap.state.value:undefined}});if(cap.type==='devices.capabilities.on_off')push('on','boolean');else if(cap.type==='devices.capabilities.toggle'&&instance)push(instance,'boolean');else if(cap.type==='devices.capabilities.range'&&instance&&p.random_access!==false)push(instance,'range');else if(cap.type==='devices.capabilities.mode'&&instance&&p.modes?.length)push(instance,'mode');else if(cap.type==='devices.capabilities.color_setting'){if(p.color_model==='rgb'||p.color_model==='hsv')push(p.color_model,'color');if(p.temperature_k)push('temperature_k','range',{range:p.temperature_k});if(p.color_scene?.scenes?.length)push('scene','mode',{modes:p.color_scene.scenes});}}return result;}
const parameterNames={on:'Питание',backlight:'Подсветка',brightness:'Яркость',volume:'Громкость',temperature:'Температура',humidity:'Влажность',temperature_k:'Температура света',rgb:'Цвет',hsv:'Цвет',scene:'Световой эффект',fan_speed:'Скорость вентилятора',thermostat:'Режим климата',work_speed:'Скорость',mute:'Без звука',pause:'Пауза',oscillation:'Вращение',controls_locked:'Блокировка',open:'Открытие',channel:'Канал',input_source:'Источник',program:'Программа',cleanup_mode:'Уборка'};
function populateCapabilities(){const device=$('homeKind').value==='device';$('deviceFields').hidden=!device;$('homeCapability').replaceChildren();if(!device)return;for(const [i,cap] of scheduleCapabilities(selectedDevice()).entries()){const name=cap.parameters.instance;const o=node('option',parameterNames[name]||name);o.value=i;$('homeCapability').append(o);}populateValue();}
function selectedCapability(){return scheduleCapabilities(selectedDevice())[Number($('homeCapability').value)];}
function colorHex(value){if(typeof value==='number')return '#'+Math.max(0,Math.min(0xffffff,value)).toString(16).padStart(6,'0');if(value&&typeof value==='object'){const h=value.h/60,s=value.s/100,v=value.v/100,c=v*s,x=c*(1-Math.abs(h%2-1)),m=v-c,parts=[[c,x,0],[x,c,0],[0,c,x],[0,x,c],[x,0,c],[c,0,x]][Math.floor(h)%6]||[0,0,0];return '#'+parts.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('');}return '#ffffff';}
function deviceValue(cap){if(!$('homeEnumField').hidden)return JSON.parse($('homeEnum').value);const input=$('homeValue'),raw=input.value;if(cap.control==='range'){const value=Number(raw);if(!raw||!Number.isFinite(value)||!input.checkValidity())throw Error('Укажите значение в диапазоне устройства');return value;}if(cap.control==='color'){if(cap.parameters.instance==='rgb')return parseInt(raw.slice(1),16);const [r,g,b]=[1,3,5].map(i=>parseInt(raw.slice(i,i+2),16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=d===0?0:max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;return {h:Math.round((h*60+360)%360),s:Math.round(max===0?0:d/max*100),v:Math.round(max*100)};}return raw;}
function populateValue(){const cap=selectedCapability(),p=cap?.parameters||{},choices=cap?.control==='boolean'?[{value:true,label:'Включить'},{value:false,label:'Выключить'}]:p.modes?.map(m=>({value:m.value,label:m.value}))||[];$('homeEnumField').hidden=!choices.length;$('homeValueField').hidden=!!choices.length;$('homeEnum').replaceChildren();for(const item of choices){const o=node('option',item.label);o.value=JSON.stringify(item.value);$('homeEnum').append(o);}const input=$('homeValue');input.type=cap?.control==='range'?'number':cap?.control==='color'?'color':'text';input.value=cap?.control==='color'?colorHex(cap.state.value):String(cap?.state?.value??p.range?.min??'');if(p.range){input.min=p.range.min;input.max=p.range.max;input.step=p.range.precision||1;}else{input.removeAttribute('min');input.removeAttribute('max');input.removeAttribute('step');}}
$('homeKind').onchange=populateHomeTargets;$('homeTarget').onchange=populateCapabilities;$('homeCapability').onchange=populateValue;
$('homeReload').onclick=async()=>{const b=$('homeReload');b.disabled=true;try{notice('homeNotice','Загрузка…');homeCatalog=await checkedCall('home_catalog');populateHomeTargets();notice('homeNotice','Список обновлён','ok');}catch(e){notice('homeNotice',e.message,'error');}finally{b.disabled=false;}};
for(const [i,d] of weekdays.entries()){const label=node('label',undefined,'day'),input=node('input');input.type='checkbox';input.value=i;input.checked=true;label.append(input,document.createTextNode(d));$('homeDays').append(label);}
function drawHomeCalendar(){const grid=$('homeCalendar');grid.replaceChildren();const value=$('homeDate').value,month=value?new Date(value+'T12:00:00'):new Date(),y=month.getFullYear(),m=month.getMonth();grid.append(node('div',month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'}),'calendar-summary'));grid.firstChild.style.gridColumn='span 7';for(const d of weekdays)grid.append(node('div',d,'weekday'));for(let n=0;n<(new Date(y,m,1).getDay()+6)%7;n++)grid.append(node('div'));for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const key=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),b=node('button',String(d),'calday'+(key===value?' marked':''));b.title='Выбрать '+key;b.onclick=()=>{$('homeDate').value=key;drawHomeCalendar();};grid.append(b);}}
$('homeRepeat').onchange=()=>{$('homeDays').hidden=$('homeRepeat').value!=='weekly';$('homeDateField').hidden=$('homeRepeat').value!=='once';$('homeCalendar').hidden=$('homeRepeat').value!=='once';drawHomeCalendar();};$('homeDate').onchange=drawHomeCalendar;
function clearHomeEdit(){editingHome=null;$('homeSave').textContent='Добавить расписание';$('homeEditCancel').hidden=true;}$('homeEditCancel').onclick=clearHomeEdit;
$('homeSave').onclick=async()=>{const b=$('homeSave');b.disabled=true;try{const kind=$('homeKind').value,target=$('homeTarget').value;if(!target)throw Error('Загрузите список и выберите цель');const once=$('homeRepeat').value==='once',entry={id:editingHome?.id,name:$('homeTarget').selectedOptions[0].textContent,kind,target_id:target,time:$('homeTime').value,date:once?$('homeDate').value:'',days:$('homeRepeat').value==='weekly'?[...$('homeDays').querySelectorAll('input:checked')].map(x=>Number(x.value)):[0,1,2,3,4,5,6],enabled:true};if(once&&!entry.date)throw Error('Выберите дату');if(kind==='device'){const cap=selectedCapability();if(!cap)throw Error('Устройство не поддерживает управляемые параметры');entry.capability_type=cap.type;entry.instance=cap.parameters.instance;entry.value=deviceValue(cap);}
  renderHome(await checkedCall('home_schedule_save',{entry}));clearHomeEdit();notice('homeNotice','Расписание сохранено','ok');}catch(e){notice('homeNotice',e.message,'error');}finally{b.disabled=false;}};
function editHome(row){if(!homeCatalog.devices.length&&!homeCatalog.scenarios.length){notice('homeNotice','Сначала обновите список устройств и сценариев','error');return;}editingHome=row;$('homeKind').value=row.kind;populateHomeTargets();$('homeTarget').value=row.target_id;populateCapabilities();if(row.kind==='device'){const caps=scheduleCapabilities(selectedDevice());$('homeCapability').value=caps.findIndex(c=>c.type===row.capability_type&&c.parameters.instance===row.instance);populateValue();$('homeValue').value=selectedCapability()?.control==='color'?colorHex(row.value):row.value;$('homeEnum').value=JSON.stringify(row.value);}$('homeTime').value=row.time;$('homeRepeat').value=row.date?'once':row.days?.length===7?'daily':'weekly';$('homeDate').value=row.date||'';for(const n of $('homeDays').querySelectorAll('input'))n.checked=row.days?.includes(Number(n.value));$('homeRepeat').onchange();$('homeSave').textContent='Сохранить изменения';$('homeEditCancel').hidden=false;}
function renderHome(result){if(!Array.isArray(result.entries))throw Error('Не удалось получить список расписаний');homeRows=result.entries;const list=$('homeList'),stamp=JSON.stringify(result);if(list.dataset.stamp===stamp)return;list.dataset.stamp=stamp;list.replaceChildren();if(result.storage_error)notice('homeNotice',result.storage_error,'error');if(!homeRows.length)list.append(node('p','Расписаний пока нет','empty'));for(const row of homeRows){const card=node('div',undefined,'home-entry');card.append(node('strong',row.name||row.target_id),node('p',row.time+' · '+(row.date||row.days.map(d=>weekdays[d]).join(', ')),'meta'),node('p',row.enabled?(row.next?'Следующий: '+new Date(row.next).toLocaleString('ru-RU'):'Время прошло'):'Выключено','meta'));if(row.result)card.append(node('p',row.result,'meta'));const actions=node('div',undefined,'actions');for(const [label,run] of [['Изменить',()=>editHome(row)],[row.enabled?'Выключить':'Включить',async()=>renderHome(await checkedCall('home_schedule_save',{entry:{...row,enabled:!row.enabled}}))],['Удалить',async()=>{renderHome(await checkedCall('home_schedule_remove',{id:row.id}));if(editingHome?.id===row.id)clearHomeEdit();}]]){const b=node('button',label,'small');b.onclick=async()=>{b.disabled=true;try{await run();}catch(e){notice('homeNotice',e.message,'error');}finally{b.disabled=false;}};actions.append(b);}card.append(actions);list.append(card);}}
for(const kind of ['timer','alarm']){const form=$(kind==='timer'?'desktopTimerForm':'desktopAlarmForm');for(const [key,label] of [['enabled','Показать на рабочем столе'],['rounded','Скруглить углы'],['on_top','Поверх других окон']]){const l=node('label',undefined,'widget-option'),input=node('input');input.type='checkbox';input.id=kind+'-'+key;l.append(input,document.createTextNode(label));form.append(l);}const l=node('label','Прозрачность: '),output=node('output','10%');output.id=kind+'-opacity-label';l.append(output);const range=node('input');range.type='range';range.id=kind+'-transparency';range.min=0;range.max=80;range.value=10;range.setAttribute('aria-label','Прозрачность виджета '+(kind==='timer'?'таймера':'будильника'));range.oninput=()=>output.textContent=range.value+'%';form.append(l,range);const save=node('button','Применить','primary');save.style.marginTop='12px';save.onclick=async()=>{save.disabled=true;try{const settings={transparency:Number(range.value)};for(const key of ['enabled','rounded','on_top'])settings[key]=$(kind+'-'+key).checked;await checkedCall('desktop_set',{kind,settings});notice('desktopNotice','Настройки виджета сохранены','ok');}catch(e){notice('desktopNotice',e.message,'error');}finally{save.disabled=false;}};form.append(save);}
async function extraRefresh(){const revision=homeRevision,sequence=++extraSequence;const [home,widgets]=await Promise.allSettled([checkedCall('home_schedule_state'),checkedCall('desktop_state')]);if(sequence!==extraSequence)return;if(home.status==='fulfilled'){if(revision===homeRevision&&!homePending)renderHome(home.value);}else notice('homeNotice',home.reason.message,'error');if(widgets.status==='fulfilled'){if(!document.activeElement.closest('#panel-desktop'))for(const kind of ['timer','alarm']){const s=widgets.value[kind];for(const key of ['enabled','rounded','on_top'])$(kind+'-'+key).checked=!!s[key];$(kind+'-transparency').value=s.transparency;$(kind+'-opacity-label').textContent=s.transparency+'%';if(s.error)notice('desktopNotice',s.error,'error');}}else notice('desktopNotice',widgets.reason.message,'error');}
syncAction();syncIdle();extraRefresh();setInterval(extraRefresh,3000);
